export function getFlagEmoji(location: string): string {
    const cleanLocation = location.trim().toLowerCase();

  const country = countryList.find((country) =>
    cleanLocation.includes(country.name.toLowerCase())
  );

  return country?.flagEmoji || "";
}

export const countryList = [
  { name: "Ain", code: "01", flagEmoji: "🇫🇷" },
  { name: "Aisne", code: "02", flagEmoji: "🇫🇷" },
  { name: "Allier", code: "03", flagEmoji: "🇫🇷" },
  { name: "Alpes-de-Haute-Provence", code: "04", flagEmoji: "🇫🇷" },
  { name: "Hautes-Alpes", code: "05", flagEmoji: "🇫🇷" },
  { name: "Alpes-Maritimes", code: "06", flagEmoji: "🇫🇷" },
  { name: "Ardèche", code: "07", flagEmoji: "🇫🇷" },
  { name: "Ardennes", code: "08", flagEmoji: "🇫🇷" },
  { name: "Ariège", code: "09", flagEmoji: "🇫🇷" },
  { name: "Aube", code: "10", flagEmoji: "🇫🇷" },
  { name: "Aude", code: "11", flagEmoji: "🇫🇷" },
  { name: "Aveyron", code: "12", flagEmoji: "🇫🇷" },
  { name: "Bouches-du-Rhône", code: "13", flagEmoji: "🇫🇷" },
  { name: "Calvados", code: "14", flagEmoji: "🇫🇷" },
  { name: "Cantal", code: "15", flagEmoji: "🇫🇷" },
  { name: "Charente", code: "16", flagEmoji: "🇫🇷" },
  { name: "Charente-Maritime", code: "17", flagEmoji: "🇫🇷" },
  { name: "Cher", code: "18", flagEmoji: "🇫🇷" },
  { name: "Corrèze", code: "19", flagEmoji: "🇫🇷" },
  { name: "Corse-du-Sud", code: "2A", flagEmoji: "🇫🇷" },
  { name: "Haute-Corse", code: "2B", flagEmoji: "🇫🇷" },
  { name: "Côte-d'Or", code: "21", flagEmoji: "🇫🇷" },
  { name: "Côtes-d'Armor", code: "22", flagEmoji: "🇫🇷" },
  { name: "Creuse", code: "23", flagEmoji: "🇫🇷" },
  { name: "Dordogne", code: "24", flagEmoji: "🇫🇷" },
  { name: "Doubs", code: "25", flagEmoji: "🇫🇷" },
  { name: "Drôme", code: "26", flagEmoji: "🇫🇷" },
  { name: "Eure", code: "27", flagEmoji: "🇫🇷" },
  { name: "Eure-et-Loir", code: "28", flagEmoji: "🇫🇷" },
  { name: "Finistère", code: "29", flagEmoji: "🇫🇷" },
  { name: "Gard", code: "30", flagEmoji: "🇫🇷" },
  { name: "Haute-Garonne", code: "31", flagEmoji: "🇫🇷" },
  { name: "Gers", code: "32", flagEmoji: "🇫🇷" },
  { name: "Gironde", code: "33", flagEmoji: "🇫🇷" },
  { name: "Hérault", code: "34", flagEmoji: "🇫🇷" },
  { name: "Ille-et-Vilaine", code: "35", flagEmoji: "🇫🇷" },
  { name: "Indre", code: "36", flagEmoji: "🇫🇷" },
  { name: "Indre-et-Loire", code: "37", flagEmoji: "🇫🇷" },
  { name: "Isère", code: "38", flagEmoji: "🇫🇷" },
  { name: "Jura", code: "39", flagEmoji: "🇫🇷" },
  { name: "Landes", code: "40", flagEmoji: "🇫🇷" },
  { name: "Loir-et-Cher", code: "41", flagEmoji: "🇫🇷" },
  { name: "Loire", code: "42", flagEmoji: "🇫🇷" },
  { name: "Haute-Loire", code: "43", flagEmoji: "🇫🇷" },
  { name: "Loire-Atlantique", code: "44", flagEmoji: "🇫🇷" },
  { name: "Loiret", code: "45", flagEmoji: "🇫🇷" },
  { name: "Lot", code: "46", flagEmoji: "🇫🇷" },
  { name: "Lot-et-Garonne", code: "47", flagEmoji: "🇫🇷" },
  { name: "Lozère", code: "48", flagEmoji: "🇫🇷" },
  { name: "Maine-et-Loire", code: "49", flagEmoji: "🇫🇷" },
  { name: "Manche", code: "50", flagEmoji: "🇫🇷" },
  { name: "Marne", code: "51", flagEmoji: "🇫🇷" },
  { name: "Haute-Marne", code: "52", flagEmoji: "🇫🇷" },
  { name: "Mayenne", code: "53", flagEmoji: "🇫🇷" },
  { name: "Meurthe-et-Moselle", code: "54", flagEmoji: "🇫🇷" },
  { name: "Meuse", code: "55", flagEmoji: "🇫🇷" },
  { name: "Morbihan", code: "56", flagEmoji: "🇫🇷" },
  { name: "Moselle", code: "57", flagEmoji: "🇫🇷" },
  { name: "Nièvre", code: "58", flagEmoji: "🇫🇷" },
  { name: "Nord", code: "59", flagEmoji: "🇫🇷" },
  { name: "Oise", code: "60", flagEmoji: "🇫🇷" },
  { name: "Orne", code: "61", flagEmoji: "🇫🇷" },
  { name: "Pas-de-Calais", code: "62", flagEmoji: "🇫🇷" },
  { name: "Puy-de-Dôme", code: "63", flagEmoji: "🇫🇷" },
  { name: "Pyrénées-Atlantiques", code: "64", flagEmoji: "🇫🇷" },
  { name: "Hautes-Pyrénées", code: "65", flagEmoji: "🇫🇷" },
  { name: "Pyrénées-Orientales", code: "66", flagEmoji: "🇫🇷" },
  { name: "Bas-Rhin", code: "67", flagEmoji: "🇫🇷" },
  { name: "Haut-Rhin", code: "68", flagEmoji: "🇫🇷" },
  { name: "Rhône", code: "69", flagEmoji: "🇫🇷" },
  { name: "Haute-Saône", code: "70", flagEmoji: "🇫🇷" },
  { name: "Saône-et-Loire", code: "71", flagEmoji: "🇫🇷" },
  { name: "Sarthe", code: "72", flagEmoji: "🇫🇷" },
  { name: "Savoie", code: "73", flagEmoji: "🇫🇷" },
  { name: "Haute-Savoie", code: "74", flagEmoji: "🇫🇷" },
  { name: "Paris", code: "75", flagEmoji: "🇫🇷" },
  { name: "Seine-Maritime", code: "76", flagEmoji: "🇫🇷" },
  { name: "Seine-et-Marne", code: "77", flagEmoji: "🇫🇷" },
  { name: "Yvelines", code: "78", flagEmoji: "🇫🇷" },
  { name: "Deux-Sèvres", code: "79", flagEmoji: "🇫🇷" },
  { name: "Somme", code: "80", flagEmoji: "🇫🇷" },
  { name: "Tarn", code: "81", flagEmoji: "🇫🇷" },
  { name: "Tarn-et-Garonne", code: "82", flagEmoji: "🇫🇷" },
  { name: "Var", code: "83", flagEmoji: "🇫🇷" },
  { name: "Vaucluse", code: "84", flagEmoji: "🇫🇷" },
  { name: "Vendée", code: "85", flagEmoji: "🇫🇷" },
  { name: "Vienne", code: "86", flagEmoji: "🇫🇷" },
  { name: "Haute-Vienne", code: "87", flagEmoji: "🇫🇷" },
  { name: "Vosges", code: "88", flagEmoji: "🇫🇷" },
  { name: "Yonne", code: "89", flagEmoji: "🇫🇷" },
  { name: "Territoire de Belfort", code: "90", flagEmoji: "🇫🇷" },
  { name: "Essonne", code: "91", flagEmoji: "🇫🇷" },
  { name: "Hauts-de-Seine", code: "92", flagEmoji: "🇫🇷" },
  { name: "Seine-Saint-Denis", code: "93", flagEmoji: "🇫🇷" },
  { name: "Val-de-Marne", code: "94", flagEmoji: "🇫🇷" },
  { name: "Val-d'Oise", code: "95", flagEmoji: "🇫🇷" },
  { name: "Guadeloupe", code: "971", flagEmoji: "🇫🇷" },
  { name: "Martinique", code: "972", flagEmoji: "🇫🇷" },
  { name: "Guyane", code: "973", flagEmoji: "🇫🇷" },
  { name: "La Réunion", code: "974", flagEmoji: "🇫🇷" },
  { name: "Mayotte", code: "976", flagEmoji: "🇫🇷" },
];